
name: workflow

on:
  push:
    branches:
      - main
  paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Lint code
        run: echo "Linting repository..."

      - name: Run unit tests
        run: echo "Running unit tests..."

      - name: Run Yarn
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip
             pip install -r requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run pyright
        run: pyright

  build_and_push-ecr-image:
    name: Continuous Delivery
    needs: integrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: latest
        run: |
        # Build the Docker container image
        #push to ECR sp that 
        # be used in deployment
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image_uri::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    Continuous_Deployment:
    needs: build_and_push-ecr-image
    runs-on: ubuntu-latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull latest image from ECR (if exists)
        run: |
          docker pull $IMAGE_URI || echo "No pre-existing image found in ECR."

      # - name : stop and remove if Running
      # run:
      #  docker rm -f cnncls || echo "No pre-existing container found."

      - name: Run Docker Image to serve users
        run: |
          docker run -d -p 8080:8080  --name=cnncls -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
      - name: Verify the deployment
        run: |
          docker system prune -f